### ISSUE TITLE
Support for Octicons Icons

### ISSUE THREAD

**Issue by jmohler1970** [tagliala/vectoriconsroundup#7]
Github has its font iconset.

https://octicons.github.com/

**Comment by tagliala** [comment]
Sorry, I'm not going to add this set at the moment. 

octicons set is not suited for a generic web application

**Comment by ihorzenich** [comment]
But Octicons mentioned in Bootstrap 4 migration guidance: http://v4-alpha.getbootstrap.com/migration/#components

**Comment by tagliala** [comment]
Hi @ihorzenich,

thanks for the feeback.

I'm tring to maintain a side-by-side comparison between popular icon fonts and Octicons switched to inline `.svg` with jekyll and rails helpers (which IMHO is probably better).
