### ISSUE TITLE
Material Design Icons

### ISSUE THREAD

**Issue by Templarian** [tagliala/vectoriconsroundup#8]
Hello, nice comparison of the open source webfont packs! Just a fix to make in the table.
- [x] Pixel Perfect at 24px

I don't know if this is something that can be fixed, but while the webfonts are stored in a separate repo, the main repo is https://github.com/Templarian/MaterialDesign (I don't really pay attentions to the stars on the webfont repo).

**Comment by tagliala** [comment]
Thanks for your feedback and for your effort in MDI :+1:
